# Generated by Django 5.2.6 on 2025-09-09 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AquisiçãoVeiculo',
            new_name='AquisicaoVeiculo',
        ),
    ]
